spring.application.name=CheckUpNow
server.port=8080

# PostgreSQL database configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/checkupnow}
spring.datasource.username=${DB_USERNAME:checkupnow}
spring.datasource.password=${DB_PASSWORD:checkupnow_local}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Auto DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Static Resources
spring.web.resources.static-locations=classpath:/static/
